-- MySQL Script generated by MySQL Workbench
-- Mon Nov 17 19:41:59 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema prisonsystem_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema prisonsystem_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prisonsystem_DB` DEFAULT CHARACTER SET utf8 ;
USE `prisonsystem_DB` ;

-- -----------------------------------------------------
-- Table `prisonsystem_DB`.`PRISION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prisonsystem_DB`.`PRISION` (
  `prision_id` INT NOT NULL AUTO_INCREMENT,
  `prision_name` VARCHAR(45) NOT NULL,
  `prision_adress` VARCHAR(45) NOT NULL,
  `prision_adressnumber` INT(5) NOT NULL,
  `prision_cep` INT(8) NOT NULL,
  `prision_city` VARCHAR(45) NOT NULL,
  `prision_state` VARCHAR(45) NOT NULL,
  `prision_country` VARCHAR(45) NOT NULL,
  `prision_capacity` BIGINT NOT NULL,
  PRIMARY KEY (`prision_id`),
  UNIQUE INDEX `idJAIL_UNIQUE` (`prision_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prisonsystem_DB`.`JAIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prisonsystem_DB`.`JAIL` (
  `jail_id` INT NOT NULL AUTO_INCREMENT,
  `jail_capacity` VARCHAR(45) NULL,
  `jail_observations` VARCHAR(45) NULL,
  `PRISION_prision_id` INT NOT NULL,
  PRIMARY KEY (`jail_id`, `PRISION_prision_id`),
  INDEX `fk_JAIL_PRISION1_idx` (`PRISION_prision_id` ASC) VISIBLE,
  CONSTRAINT `fk_JAIL_PRISION1`
    FOREIGN KEY (`PRISION_prision_id`)
    REFERENCES `prisonsystem_DB`.`PRISION` (`prision_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prisonsystem_DB`.`PRISIONER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prisonsystem_DB`.`PRISIONER` (
  `prisioner_id` INT NOT NULL AUTO_INCREMENT,
  `prisioner_name` VARCHAR(60) NOT NULL,
  `prisioner_adress` VARCHAR(45) NULL,
  `prisioner_adressnumber` INT(6) NULL,
  `prisioner_state` VARCHAR(45) NULL,
  `prisioner_country` VARCHAR(45) NULL,
  `prisioner_city` VARCHAR(45) NULL,
  `prisioner_birthdate` DATE NULL,
  `prisioner_bloodtype` VARCHAR(3) NULL,
  `prisioner_healthobservations` TEXT NULL,
  `prisioner_entrance` DATE NULL,
  `prisioner_exit` DATE NULL,
  `prision_id` INT NOT NULL,
  `jail_id` INT NOT NULL,
  `prisioner_cep` INT(8) NULL,
  PRIMARY KEY (`prisioner_id`, `prision_id`, `jail_id`),
  UNIQUE INDEX `idPRISIONER_UNIQUE` (`prisioner_id` ASC) VISIBLE,
  INDEX `fk_PRISIONER_PRISION1_idx` (`prision_id` ASC) VISIBLE,
  INDEX `fk_PRISIONER_JAIL1_idx` (`jail_id` ASC) VISIBLE,
  CONSTRAINT `fk_PRISIONER_PRISION1`
    FOREIGN KEY (`prision_id`)
    REFERENCES `prisonsystem_DB`.`PRISION` (`prision_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRISIONER_JAIL1`
    FOREIGN KEY (`jail_id`)
    REFERENCES `prisonsystem_DB`.`JAIL` (`jail_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prisonsystem_DB`.`EMPLOYEE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prisonsystem_DB`.`EMPLOYEE` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `employee_name` VARCHAR(45) NOT NULL,
  `employee_role` VARCHAR(45) NOT NULL,
  `employee_adress` VARCHAR(45) NOT NULL,
  `employee_adressnumber` INT(5) NOT NULL,
  `employee_city` VARCHAR(45) NOT NULL,
  `employee_state` VARCHAR(45) NOT NULL,
  `employee_country` VARCHAR(45) NOT NULL,
  `employee_cep` INT(8) NOT NULL,
  `employee_birthdate` DATE NOT NULL,
  `employee_bloodtype` VARCHAR(3) NOT NULL,
  `employee_healthobservations` TEXT NOT NULL,
  `prision_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`, `prision_id`),
  UNIQUE INDEX `idEMPLOYEE_UNIQUE` (`employee_id` ASC) VISIBLE,
  INDEX `fk_EMPLOYEE_PRISION1_idx` (`prision_id` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLOYEE_PRISION1`
    FOREIGN KEY (`prision_id`)
    REFERENCES `prisonsystem_DB`.`PRISION` (`prision_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prisonsystem_DB`.`MEETING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prisonsystem_DB`.`MEETING` (
  `meeting_id` INT NOT NULL AUTO_INCREMENT,
  `meeting_personname` VARCHAR(45) NOT NULL,
  `meeting_observations` VARCHAR(45) NULL,
  `meeting_datetime` DATETIME NOT NULL,
  `prisioner_id` INT NOT NULL,
  `prision_id` INT NOT NULL,
  PRIMARY KEY (`meeting_id`, `prisioner_id`, `prision_id`),
  INDEX `fk_MEETING_PRISIONER1_idx` (`prisioner_id` ASC, `prision_id` ASC) VISIBLE,
  CONSTRAINT `fk_MEETING_PRISIONER1`
    FOREIGN KEY (`prisioner_id` , `prision_id`)
    REFERENCES `prisonsystem_DB`.`PRISIONER` (`prisioner_id` , `prision_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prisonsystem_DB`.`PRISIONER_ACTIVITY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prisonsystem_DB`.`PRISIONER_ACTIVITY` (
  `prisioneractivity_id` INT NOT NULL AUTO_INCREMENT,
  `prisioneractivity_name` VARCHAR(45) NULL,
  `prisioneractivity_observations` TEXT NULL,
  `prisioneractivity_datetime` DATETIME NULL,
  `prisioneractivity_reductiondays` VARCHAR(2) NULL,
  `prisioner_id` INT NOT NULL,
  `prision_id` INT NOT NULL,
  `jail_id` INT NOT NULL,
  PRIMARY KEY (`prisioneractivity_id`, `prisioner_id`, `prision_id`, `jail_id`),
  INDEX `fk_PRISIONER_ACTIVITY_PRISIONER1_idx` (`prisioner_id` ASC, `prision_id` ASC, `jail_id` ASC) VISIBLE,
  CONSTRAINT `fk_PRISIONER_ACTIVITY_PRISIONER1`
    FOREIGN KEY (`prisioner_id` , `prision_id` , `jail_id`)
    REFERENCES `prisonsystem_DB`.`PRISIONER` (`prisioner_id` , `prision_id` , `jail_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prisonsystem_DB`.`OCURRENCY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prisonsystem_DB`.`OCURRENCY` (
  `ocurrency_id` INT NOT NULL AUTO_INCREMENT,
  `ocurrency_name` VARCHAR(60) NOT NULL,
  `ocurrency_observation` TEXT NOT NULL,
  `ocurrency_datetime` DATETIME NOT NULL,
  `prision_id` INT NOT NULL,
  `prisioner_id` INT NOT NULL,
  `jail_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`ocurrency_id`, `employee_id`),
  INDEX `fk_OCURRENCY_PRISION1_idx` (`prision_id` ASC) VISIBLE,
  INDEX `fk_OCURRENCY_PRISIONER1_idx` (`prisioner_id` ASC) VISIBLE,
  INDEX `fk_OCURRENCY_JAIL1_idx` (`jail_id` ASC) VISIBLE,
  INDEX `fk_OCURRENCY_EMPLOYEE1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_OCURRENCY_PRISION1`
    FOREIGN KEY (`prision_id`)
    REFERENCES `prisonsystem_DB`.`PRISION` (`prision_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OCURRENCY_PRISIONER1`
    FOREIGN KEY (`prisioner_id`)
    REFERENCES `prisonsystem_DB`.`PRISIONER` (`prisioner_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OCURRENCY_JAIL1`
    FOREIGN KEY (`jail_id`)
    REFERENCES `prisonsystem_DB`.`JAIL` (`jail_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OCURRENCY_EMPLOYEE1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `prisonsystem_DB`.`EMPLOYEE` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prisonsystem_DB`.`EMPLOYEE_ACTIVITY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prisonsystem_DB`.`EMPLOYEE_ACTIVITY` (
  `employeeactivity_id` INT NOT NULL AUTO_INCREMENT,
  `employeeactivity_name` VARCHAR(45) NOT NULL,
  `employeeactivity_description` TEXT NOT NULL,
  `employee_id` INT NOT NULL,
  `prision_id` INT NOT NULL,
  `employeeactivity_datetime` DATETIME NOT NULL,
  PRIMARY KEY (`employeeactivity_id`, `employee_id`, `prision_id`),
  INDEX `fk_EMPLOYEE_ACTIVITY_EMPLOYEE1_idx` (`employee_id` ASC, `prision_id` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLOYEE_ACTIVITY_EMPLOYEE1`
    FOREIGN KEY (`employee_id` , `prision_id`)
    REFERENCES `prisonsystem_DB`.`EMPLOYEE` (`employee_id` , `prision_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prisonsystem_DB`.`MOVEMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prisonsystem_DB`.`MOVEMENT` (
  `movement_id` INT NOT NULL AUTO_INCREMENT,
  `movement_name` VARCHAR(45) NOT NULL,
  `movement_description` TEXT NOT NULL,
  `movement_adress` VARCHAR(45) NOT NULL,
  `movement_adressnumber` INT(5) NOT NULL,
  `movement_cep` INT(8) NOT NULL,
  `movement_datetime` DATETIME NOT NULL,
  `prision_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`movement_id`),
  INDEX `fk_MOVEMENT_PRISION1_idx` (`prision_id` ASC) VISIBLE,
  INDEX `fk_MOVEMENT_EMPLOYEE1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_MOVEMENT_PRISION1`
    FOREIGN KEY (`prision_id`)
    REFERENCES `prisonsystem_DB`.`PRISION` (`prision_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MOVEMENT_EMPLOYEE1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `prisonsystem_DB`.`EMPLOYEE` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prisonsystem_DB`.`prisioner_movement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prisonsystem_DB`.`prisioner_movement` (
  `prisioner_id` INT NOT NULL,
  `prision_id` INT NOT NULL,
  `movement_id` INT NOT NULL,
  PRIMARY KEY (`prisioner_id`, `prision_id`, `movement_id`),
  INDEX `fk_PRISIONER_has_MOVEMENT_MOVEMENT1_idx` (`movement_id` ASC) VISIBLE,
  INDEX `fk_PRISIONER_has_MOVEMENT_PRISIONER1_idx` (`prisioner_id` ASC, `prision_id` ASC) VISIBLE,
  CONSTRAINT `fk_PRISIONER_has_MOVEMENT_PRISIONER1`
    FOREIGN KEY (`prisioner_id` , `prision_id`)
    REFERENCES `prisonsystem_DB`.`PRISIONER` (`prisioner_id` , `prision_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRISIONER_has_MOVEMENT_MOVEMENT1`
    FOREIGN KEY (`movement_id`)
    REFERENCES `prisonsystem_DB`.`MOVEMENT` (`movement_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prisonsystem_DB`.`PRISIONER_AUDIT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prisonsystem_DB`.`PRISIONER_AUDIT` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `prisioner_id` INT NOT NULL,
  `prision_id` INT NOT NULL,
  PRIMARY KEY (`prisioner_id`, `prision_id`),
  CONSTRAINT `fk_timestamps_PRISIONER1`
    FOREIGN KEY (`prisioner_id` , `prision_id`)
    REFERENCES `prisonsystem_DB`.`PRISIONER` (`prisioner_id` , `prision_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `prisonsystem_DB`.`PRISION_AUDIT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prisonsystem_DB`.`PRISION_AUDIT` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `prision_id` INT NOT NULL,
  PRIMARY KEY (`prision_id`),
  CONSTRAINT `fk_PRISION_AUDIT_PRISION1`
    FOREIGN KEY (`prision_id`)
    REFERENCES `prisonsystem_DB`.`PRISION` (`prision_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `prisonsystem_DB`.`EMPLOYEE_AUDIT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prisonsystem_DB`.`EMPLOYEE_AUDIT` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `employee_id` INT NOT NULL,
  `prision_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`, `prision_id`),
  CONSTRAINT `fk_timestamps_EMPLOYEE1`
    FOREIGN KEY (`employee_id` , `prision_id`)
    REFERENCES `prisonsystem_DB`.`EMPLOYEE` (`employee_id` , `prision_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `prisonsystem_DB`.`OCURRENCY_AUDIT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prisonsystem_DB`.`OCURRENCY_AUDIT` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `ocurrency_id` INT NOT NULL,
  PRIMARY KEY (`ocurrency_id`),
  CONSTRAINT `fk_OCURRENCY_AUDIT_OCURRENCY1`
    FOREIGN KEY (`ocurrency_id`)
    REFERENCES `prisonsystem_DB`.`OCURRENCY` (`ocurrency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `prisonsystem_DB`.`JAIL_AUDIT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prisonsystem_DB`.`JAIL_AUDIT` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `jail_id` INT NOT NULL,
  `prision_id` INT NOT NULL,
  PRIMARY KEY (`jail_id`, `prision_id`),
  CONSTRAINT `fk_JAIL_AUDIT_JAIL1`
    FOREIGN KEY (`jail_id` , `prision_id`)
    REFERENCES `prisonsystem_DB`.`JAIL` (`jail_id` , `PRISION_prision_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `prisonsystem_DB`.`MOVEMENT_AUDIT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prisonsystem_DB`.`MOVEMENT_AUDIT` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `movement_id` INT NOT NULL,
  PRIMARY KEY (`movement_id`),
  CONSTRAINT `fk_MOVEMENT_AUDIT_MOVEMENT1`
    FOREIGN KEY (`movement_id`)
    REFERENCES `prisonsystem_DB`.`MOVEMENT` (`movement_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `prisonsystem_DB`.`PRISIONERACTIVITY_AUDIT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prisonsystem_DB`.`PRISIONERACTIVITY_AUDIT` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `prisioneractivity_id` INT NOT NULL,
  `prisioner_id` INT NOT NULL,
  `prision_id` INT NOT NULL,
  `jail_id` INT NOT NULL,
  PRIMARY KEY (`prisioneractivity_id`, `prisioner_id`, `prision_id`, `jail_id`),
  CONSTRAINT `fk_PRISIONERACTIVITY_AUDIT_PRISIONER_ACTIVITY1`
    FOREIGN KEY (`prisioneractivity_id` , `prisioner_id` , `prision_id` , `jail_id`)
    REFERENCES `prisonsystem_DB`.`PRISIONER_ACTIVITY` (`prisioneractivity_id` , `prisioner_id` , `prision_id` , `jail_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `prisonsystem_DB`.`MEETING_AUDIT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prisonsystem_DB`.`MEETING_AUDIT` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL,
  `meeting_id` INT NOT NULL,
  `prisioner_id` INT NOT NULL,
  `prision_id` INT NOT NULL,
  PRIMARY KEY (`meeting_id`, `prisioner_id`, `prision_id`),
  CONSTRAINT `fk_timestamps_1_MEETING1`
    FOREIGN KEY (`meeting_id` , `prisioner_id` , `prision_id`)
    REFERENCES `prisonsystem_DB`.`MEETING` (`meeting_id` , `prisioner_id` , `prision_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
